language: C

matrix:
  include:
  - os: linux
    dist: bionic
    compiler: gcc
  - os: linux
    dist: bionic
    compiler: clang

before_install: sudo apt-get update -y && sudo apt-get upgrade

script: make regression

notifications:
  email: false
